name: fcpgtools_base
channels:
  - conda-forge
  - default

dependencies:
  - python =3.9 # 3.10 caused conflicts with taudem on conda-forge
  - poetry
  - pip
  - taudem =5.3.8  # Limits to older versions of gdal =3.1.4; rasterio =1.2.1
  - geopandas >=0.12.1
  - rasterio =1.2